---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
  become: yes
  tags:
  - mattermost
  - check

- name: Ensure Docker Compose is installed
  apt:
    name: docker-compose
    state: present
  become: yes
  tags:
  - mattermost
  - check

- name: Create Mattermost directory
  file:
    path: "{{ mattermost_dir }}"
    state: directory
    mode: '2775'
    owner: root
    group: docker
    recurse: yes
  become: yes
  tags:
  - mattermost
  - mattermost-dir

- name: Create docker directory
  file:
    path: "{{ docker_dir }}"
    state: directory
    mode: '2775'
    owner: root
    group: docker
    recurse: yes
  become: yes
  tags:
  - mattermost
  - docker-dir

- name: Set ownership of Mattermost volumes
  file:
    path: "{{ item }}"
    owner: 2000
    group: 2000
    recurse: yes
  loop:
    - "{{ mattermost_volume_dir }}"
    - "{{ MATTERMOST_CONFIG_PATH }}"
    - "{{ MATTERMOST_DATA_PATH }}"
    - "{{ MATTERMOST_LOGS_PATH }}"
    - "{{ MATTERMOST_PLUGINS_PATH }}"
    - "{{ MATTERMOST_CLIENT_PLUGINS_PATH }}"
    - "{{ MATTERMOST_BLEVE_INDEXES_PATH }}"
  become: yes
  tags:
    - mattermost
    - volumes

- name: Copy Compose file
  copy:
    src: "{{ compose_name }}"
    dest: "{{ compose_dest }}"
    mode: '0640'
    owner: root
    group: docker
  become: yes
  tags:
  - mattermost
  - copy-compose

- name: Copy .env file
  copy:
    src: .env
    dest: "{{ env_dest }}"
    mode: '0640'
    owner: root
    group: docker
  become: yes
  tags:
  - mattermost
  - copy-env

- name: Pull mattermost and postgres Docker images
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dest }}"
    pull: always
  tags:
  - mattermost
  - pull-images

- name: Start mattermost and postgres with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ compose_dest }}"
    state: present
    remove_orphans: true
  tags:
  - mattermost
  - run-container