      services:
        # Prosody XMPP server
        prosody:
          container_name: prosody
          image: jitsi/prosody:${PROSODY_VERSION}
          restart: ${RESTART_POLICY}
          volumes:
            - ${CONFIG}/prosody/config:/config:Z
            - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
          expose:
            - "5222"
            - "5347"
            - "5280"
          environment:
            - ENABLE_AUTH=${ENABLE_AUTH}
            - AUTH_TYPE=${AUTH_TYPE}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_GUEST_DOMAIN=${XMPP_GUEST_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
            - XMPP_MUC_DOMAIN=${XMPP_MUC_DOMAIN}
            - TZ=${TZ}
            - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
            - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
            - JVB_AUTH_USER=${JVB_AUTH_USER}
            - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
          labels:
            - "traefik.enable=true"
            # BOSH endpoint (/http-bind and /xmpp-websocket)
            - "traefik.http.routers.jitsi-bosh.rule=Host(`call.a;ch.com`) && (PathPrefix(`/http-bind`) || PathPrefix(`/xmpp-websocket`))"
            - "traefik.http.routers.jitsi-bosh.tls=true"
            - "traefik.http.routers.jitsi-bosh.entrypoints=web-secure"
            - "traefik.http.routers.jitsi-bosh.tls.certresolver=le"
            - "traefik.http.services.jitsi-bosh.loadbalancer.server.port=5280"     
          networks:
            - meet.jitsi
            - web-network

        # Jicofo (focus component)
        jicofo:
          container_name: jicofo
          image: jitsi/jicofo:${JICOFO_VERSION}
          restart: ${RESTART_POLICY}
          volumes:
            - ${CONFIG}/jicofo:/config:Z
          environment:
            - ENABLE_AUTH=${ENABLE_AUTH}
            - AUTH_TYPE=${AUTH_TYPE}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
            - XMPP_SERVER=${XMPP_SERVER}
            - TZ=${TZ}
            - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
            - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}  
          depends_on:
            - prosody
          networks:
            - meet.jitsi

        # JVB (Video Bridge)
        jvb:
          container_name: jvb
          image: jitsi/jvb:${JVB_VERSION}
          restart: ${RESTART_POLICY}  
          volumes:
            - ${CONFIG}/jvb:/config:Z
          environment:
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
            - XMPP_SERVER=${XMPP_SERVER}
            - JVB_PORT=${JVB_PORT}
            - TZ=${TZ}
            - JVB_AUTH_USER=${JVB_AUTH_USER}
            - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
          depends_on:
            - prosody
          networks:
            - meet.jitsi

        # Web UI
        web:
          container_name: jitsi
          image: jitsi/web:${JITSI_VERSION}
          restart: ${RESTART_POLICY}
          volumes:
            - ${CONFIG}/web:/co nfig:ro
          environment:
            - ENABLE_AUTH=${ENABLE_AUTH}
            - ENABLE_GUESTS=${ENABLE_GUESTS}
            - AUTH_TYPE=${AUTH_TYPE}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
            - XMPP_GUEST_DOMAIN=${XMPP_GUEST_DOMAIN}
            - TZ=${TZ}
            - PUBLIC_URL=${PUBLIC_URL}
            - ENABLE_XMPP_WEBSOCKET=${ENABLE_XMPP_WEBSOCKET}
            - XMPP_BOSH_URL_BASE=${XMPP_BOSH_URL_BASE}
            - XMPP_WEB_SOCKET=${XMPP_WEB_SOCKET}
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jitsi.rule=Host(`call.alch.com`)"
            - "traefik.http.routers.jitsi.entrypoints=web-secure"
            - "traefik.http.routers.jitsi.tls=true"
            - "traefik.http.routers.jitsi.tls.certresolver=le"
            - "traefik.http.services.jitsi.loadbalancer.server.port=80"
          depends_on:
            - prosody
            - jicofo
            - jvb
          networks:
            - meet.jitsi
            - web-network

      networks:
        meet.jitsi:
          name: meet.jitsi
          driver: bridge
        web-network:
          external: true
