---
- name: Create lemp directory
  become: true
  file:
    path: "{{ PATH }}"
    state: directory
  tags: nginx-dir

- name: Copy nginx templates
  become: yes
  template:
    src: nginx.conf.j2
    dest: "{{ PATH }}/nginx.conf"
    force: yes
  tags: nginx-templates

- name: NGINX container
  docker_container:
    name: nginx
    image: "nginx:{{ NGINX_VERSION }}"
    ports:
      - '{{ NGINX_PORT }}:80'
    state: started
    recreate: true
    restart_policy: on-failure
    networks:
      - name: "{{ NETWORK }}"
    volumes:
      - "{{ PATH }}:{{ PATH }}:ro"
  tags: nginx-run
